[tool.black]
line-length = 100
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/build/
^/dist/
^/\.eggs/
^/\.git/
^/\.hg/
^/\.mypy_cache/
^/\.nox/
^/\.tox/
^/\.venv/
^/venv/
'''

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip = [
    ".git",
    ".eggs",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".tox",
    ".venv",
    "venv",
    "build",
    "dist"
]

[tool.pytest.ini_options]
testpaths = ["./tests/"]
filterwarnings = ["ignore::DeprecationWarning", "ignore:Support for class-based"]
